<?php
class ModelBossthemesBossEditorthemes extends Model
{
    private $color_themes = array(
        'theme1' => array(
            'g_bg_color'                    => 'e8f5ff',
            'g_text_color'                  => 'f12b63',
            'g_link_normal_color'        	=> 'edf3f5',
            'g_link_hover_color'        	=> 'e6f6fa',
            'g_border_color'              	=> '103e47',
            'g_color_1_normal'             	=> '4cb1ca',
            'g_color_2_normal'               => '4cb1ca',
            'g_color_3_normal'              	=> 'ffffff',
			'g_color_1_hover'             	=> '4cb1ca',
            'g_color_2_hover'               => '4cb1ca',
            'g_color_3_hover'              	=> 'ffffff',
            'h_bg_color'             		=> 'f12b63',
            'h_color_1_normal'        		=> '202020',
            'h_color_2_normal'       		=> '38B0E3',
            'h_color_3_normal' 				=> 'ffffff',
			'h_color_1_hover'        		=> '202020',
            'h_color_2_hover'       		=> '38B0E3',
            'h_color_3_hover' 				=> 'ffffff',
			'f_bg_color'                    => '4cb1ca',
            'f_color_1_normal'               => '363a3b',
            'f_color_2_normal'        		=> '1e27d6',
            'f_color_3_normal'        		=> 'e6f6fa',
			'f_color_1_hover'               => '363a3b',
            'f_color_2_hover'        		=> '1e27d6',
            'f_color_3_hover'        		=> 'e6f6fa',
            'm_bg_normal_color'             => '585858',
            'm_bg_hover_color'             	=> '4cb1ca',
            'm_text_normal_color'           => 'ffffff',
            'm_text_hover_color'            => 'ffffff',
            'm_bg_normal_color_drop'        => 'f12b63',
			'm_bg_hover_color_drop'         => 'f12b63',
            'm_text_normal_color_1'        	=> 'ffffff',
            'm_text_hover_color_1'       	=> 'f12b63',
            'm_text_normal_color_2' 		=> 'ffffff',
			'm_text_hover_color_2'          => '71b013',
            's_bg_color'                  	=> 'ff9900',
            's_but_normal_color'         	=> 'f9fff2',
            's_but_hover_color'        		=> 'dcf5ce',
            's_color_1'              		=> '385217',
			's_color_2'              		=> '71b013',
            's_color_3'               		=> 'ff9900',
            'p_name_color'         			=> '38B0E3',
            'p_des_color'        			=> 'dcf5ce',
            'p_price_color'              	=> '385217',
            'p_text_price_color'            => '65a819',
            'p_spec_color'                  => 'bfe388',
            'p_text_spec_color'             => '395215',
            'p_but_normal_color'            => 'AF0600',
            'p_but_hover_color'     		=> 'ffffff',
            'p_text_but_normal_color'       => 'ffffff',
			'p_text_but_hover_color'        => '71b013',
            't_page_color'                  => 'ff9900',
            't_block_color'         		=> 'f9fff2',
			't_bread_color'         		=> 'f9fff2',
            't_bread_normal_color_1'        => 'dcf5ce',
            't_bread_hover_color_1'         => '385217',
            't_bread_normal_color_2'        => '65a819',
            't_bread_hover_color_2'         => 'bfe388'
        ),
        'theme2' => array(
            'g_bg_color'                    => 'e4f2e4',
            'g_text_color'                  => 'f12b63',
            'g_link_normal_color'        	=> 'edf3f5',
            'g_link_hover_color'        	=> 'e6f6fa',
            'g_border_color'              	=> '103e47',
            'g_color_1_normal'             	=> '4cb1ca',
            'g_color_2_normal'               => '4cb1ca',
            'g_color_3_normal'              	=> 'ffffff',
			'g_color_1_hover'             	=> '4cb1ca',
            'g_color_2_hover'               => '4cb1ca',
            'g_color_3_hover'              	=> 'ffffff',
			'h_bg_color'             		=> 'f12b63',
            'h_color_1_normal'        		=> '202020',
            'h_color_2_normal'       		=> '38B0E3',
            'h_color_3_normal' 				=> 'ffffff',
			'h_color_1_hover'        		=> '202020',
            'h_color_2_hover'       		=> '38B0E3',
            'h_color_3_hover' 				=> 'ffffff',
			'f_bg_color'                    => '4cb1ca',
            'f_color_1_normal'               => '363a3b',
            'f_color_2_normal'        		=> '1e27d6',
            'f_color_3_normal'        		=> 'e6f6fa',
			'f_color_1_hover'               => '363a3b',
            'f_color_2_hover'        		=> '1e27d6',
            'f_color_3_hover'        		=> 'e6f6fa',
            'm_bg_normal_color'             => '585858',
            'm_bg_hover_color'             	=> '4cb1ca',
            'm_text_normal_color'           => '55c94c',
            'm_text_hover_color'            => 'ffffff',
            'm_bg_normal_color_drop'        => 'f12b63',
			'm_bg_hover_color_drop'         => 'f12b63',
            'm_text_normal_color_1'        	=> 'ffffff',
            'm_text_hover_color_1'       	=> 'f12b63',
            'm_text_normal_color_2' 		=> 'ffffff',
			'm_text_hover_color_2'          => '71b013',
            's_bg_color'                  	=> 'ff9900',
            's_but_normal_color'         	=> 'f9fff2',
            's_but_hover_color'        		=> 'dcf5ce',
            's_color_1'              		=> '385217',
			's_color_2'              		=> '71b013',
            's_color_3'               		=> 'ff9900',
            'p_name_color'         			=> '54c94c',
            'p_des_color'        			=> 'dcf5ce',
            'p_price_color'              	=> '385217',
            'p_text_price_color'            => '65a819',
            'p_spec_color'                  => 'bfe388',
            'p_text_spec_color'             => '395215',
            'p_but_normal_color'            => 'ff9900',
            'p_but_hover_color'     		=> 'ffffff',
            'p_text_but_normal_color'       => 'ff9900',
			'p_text_but_hover_color'        => '71b013',
            't_page_color'                  => 'ff9900',
            't_block_color'         		=> 'f9fff2',
			't_bread_color'         		=> 'f9fff2',
            't_bread_normal_color_1'        => 'dcf5ce',
            't_bread_hover_color_1'         => '385217',
            't_bread_normal_color_2'        => '65a819',
            't_bread_hover_color_2'         => 'bfe388'
            
        ),
        'theme3' => array(
            'g_bg_color'                    => 'f2d9b3',
            'g_text_color'                  => 'f12b63',
            'g_link_normal_color'        	=> 'edf3f5',
            'g_link_hover_color'        	=> 'e6f6fa',
            'g_border_color'              	=> '103e47',
            'g_color_1_normal'             	=> '4cb1ca',
            'g_color_2_normal'               => '4cb1ca',
            'g_color_3_normal'              	=> 'ffffff',
			'g_color_1_hover'             	=> '4cb1ca',
            'g_color_2_hover'               => '4cb1ca',
            'g_color_3_hover'              	=> 'ffffff',
            'h_bg_color'             		=> 'f12b63',
            'h_color_1_normal'        		=> '202020',
            'h_color_2_normal'       		=> '38B0E3',
            'h_color_3_normal' 				=> 'ffffff',
			'h_color_1_hover'        		=> '202020',
            'h_color_2_hover'       		=> '38B0E3',
            'h_color_3_hover' 				=> 'ffffff',
			'f_bg_color'                    => '4cb1ca',
            'f_color_1_normal'               => '363a3b',
            'f_color_2_normal'        		=> '1e27d6',
            'f_color_3_normal'        		=> 'e6f6fa',
			'f_color_1_hover'               => '363a3b',
            'f_color_2_hover'        		=> '1e27d6',
            'f_color_3_hover'        		=> 'e6f6fa',
            'm_bg_normal_color'             => '103e47',
            'm_bg_hover_color'             	=> '4cb1ca',
            'm_text_normal_color'           => 'ff9900',
            'm_text_hover_color'            => 'ffffff',
            'm_bg_normal_color_drop'        => 'f12b63',
			'm_bg_hover_color_drop'         => 'f12b63',
            'm_text_normal_color_1'        	=> 'ffffff',
            'm_text_hover_color_1'       	=> 'f12b63',
            'm_text_normal_color_2' 		=> 'ffffff',
			'm_text_hover_color_2'          => '71b013',
            's_bg_color'                  	=> 'ff9900',
            's_but_normal_color'         	=> 'f9fff2',
            's_but_hover_color'        		=> 'dcf5ce',
            's_color_1'              		=> '385217',
			's_color_2'              		=> '71b013',
            's_color_3'               		=> 'ff9900',
            'p_name_color'         			=> 'ed620c',
            'p_des_color'        			=> 'dcf5ce',
            'p_price_color'              	=> '385217',
            'p_text_price_color'            => '65a819',
            'p_spec_color'                  => 'bfe388',
            'p_text_spec_color'             => '395215',
            'p_but_normal_color'            => '08a10b',
            'p_but_hover_color'     		=> 'ffffff',
            'p_text_but_normal_color'       => 'f2d309',
			'p_text_but_hover_color'        => '71b013',
            't_page_color'                  => 'ff9900',
            't_block_color'         		=> 'f9fff2',
			't_bread_color'         		=> 'f9fff2',
            't_bread_normal_color_1'        => 'dcf5ce',
            't_bread_hover_color_1'         => '385217',
            't_bread_normal_color_2'        => '65a819',
            't_bread_hover_color_2'         => 'bfe388'
        ),
        'theme4' => array(
            'g_bg_color'                    => 'ffbdd3',
            'g_text_color'                  => 'f12b63',
            'g_link_normal_color'        	=> 'edf3f5',
            'g_link_hover_color'        	=> 'e6f6fa',
            'g_border_color'              	=> '103e47',
            'g_color_1_normal'             	=> '4cb1ca',
            'g_color_2_normal'               => '4cb1ca',
            'g_color_3_normal'              	=> 'ffffff',
			'g_color_1_hover'             	=> '4cb1ca',
            'g_color_2_hover'               => '4cb1ca',
            'g_color_3_hover'              	=> 'ffffff',
            'h_bg_color'             		=> 'f12b63',
            'h_color_1_normal'        		=> '202020',
            'h_color_2_normal'       		=> '38B0E3',
            'h_color_3_normal' 				=> 'ffffff',
			'h_color_1_hover'        		=> '202020',
            'h_color_2_hover'       		=> '38B0E3',
            'h_color_3_hover' 				=> 'ffffff',
			'f_bg_color'                    => '4cb1ca',
            'f_color_1_normal'               => '363a3b',
            'f_color_2_normal'        		=> '1e27d6',
            'f_color_3_normal'        		=> 'e6f6fa',
			'f_color_1_hover'               => '363a3b',
            'f_color_2_hover'        		=> '1e27d6',
            'f_color_3_hover'        		=> 'e6f6fa',
            'm_bg_normal_color'             => '585858',
            'm_bg_hover_color'             	=> '4cb1ca',
            'm_text_normal_color'           => 'ff0000',
            'm_text_hover_color'            => 'ffffff',
            'm_bg_normal_color_drop'        => 'f12b63',
			'm_bg_hover_color_drop'         => 'f12b63',
            'm_text_normal_color_1'        	=> 'ffffff',
            'm_text_hover_color_1'       	=> 'f12b63',
            'm_text_normal_color_2' 		=> 'ffffff',
			'm_text_hover_color_2'          => '71b013',
            's_bg_color'                  	=> 'ff9900',
            's_but_normal_color'         	=> 'f9fff2',
            's_but_hover_color'        		=> 'dcf5ce',
            's_color_1'              		=> '385217',
			's_color_2'              		=> '71b013',
            's_color_3'               		=> 'ff9900',
            'p_name_color'         			=> 'ff0000',
            'p_des_color'        			=> 'dcf5ce',
            'p_price_color'              	=> '385217',
            'p_text_price_color'            => '65a819',
            'p_spec_color'                  => 'bfe388',
            'p_text_spec_color'             => '395215',
            'p_but_normal_color'            => 'bdb8bf',
            'p_but_hover_color'     		=> 'ffffff',
            'p_text_but_normal_color'       => '0022ff',
			'p_text_but_hover_color'        => '71b013',
            't_page_color'                  => 'ff9900',
            't_block_color'         		=> 'f9fff2',
			't_bread_color'         		=> 'f9fff2',
            't_bread_normal_color_1'        => 'dcf5ce',
            't_bread_hover_color_1'         => '385217',
            't_bread_normal_color_2'        => '65a819',
            't_bread_hover_color_2'         => 'bfe388'
        )
    );
	
	private $background = array(
            'g_bg_image_1'       => 'back_1.png',
            'g_bg_image_2'       => 'back_2.png',
            'g_bg_image_3'       => 'back_3.png',
            'g_bg_image_4'       => 'back_4.png',
            'g_bg_image_5'       => 'back_5.png',
            'g_bg_image_6'       => 'back_6.png',
			'g_bg_image_7'       => 'back_7.png',
            'g_bg_image_8'       => 'back_8.png',
            'g_bg_image_9'       => 'back_9.png',
            'g_bg_image_10'       => 'back_10.png',
            'g_bg_image_11'       => 'back_11.png',
            'g_bg_image_12'       => 'back_12.png',
			'g_bg_image_13'       => 'back_13.png',
            'g_bg_image_14'       => 'back_14.png',
            'g_bg_image_15'       => 'back_15.png'
    );

    private $theme_name;
	

    private $theme_names = array(
        'theme1' => 'Blue',
        'theme2' => 'Green',
        'theme3' => 'Orange',
        'theme4' => 'Red'
    );

    public function setThemeName($theme_name)
    {
        $this->theme_name = $theme_name;
    }

   
    public function getThemeNames()
    {
        return $this->theme_names;
    }

    public function getColorThemes()
    {
        return $this->color_themes;
    }
	
	public function getBackgrounds()
    {
        return $this->background;
    }

}